change icons and image sizes, refactoring #45
ImLumi/team_todo pull request #46
Opened 2022-02-04 16:54 UTC by Storno00

2022-02-04 16:55 UTC, agie83 approved these changes

2022-02-04 17:52 UTC, ImLumi requested changes
.icon osztály rossz helyen van

2022-02-04 17:52 UTC, ImLumi commented on public/css/general.css
> +.icon {
Ez is mehetne a util.css-be, vagy a createtodo.css be

2022-02-05 12:51 UTC, ImLumi approved these changes

2022-02-05 12:51 UTC, merged